# docker container for developers (includes src code)
FROM sophianunner/hangman:basic AS devBuild
WORKDIR /
COPY CMakeLists.txt main ./
RUN cmake . && make

# docker container for end-users (no source code, only running binary)
FROM ubuntu:bionic AS cusBuild
WORKDIR /opt/Hangman
COPY --from=devBuild /main/Hangman ./
CMD ["./Hangman"]