# docker container for developers (includes src code)
FROM sophianunner/hangman:basic AS devBuild
RUN mkdir /src
WORKDIR /src
RUN mkdir main
COPY CMakeLists.txt ./
COPY main ./main
RUN ls
RUN mkdir build
RUN cd build && cmake ..
#RUN cmake .
RUN make
#RUN cmake . && make

# docker container for end-users (no source code, only running binary)
FROM ubuntu:bionic AS cusBuild
WORKDIR /opt/Hangman
COPY --from=devBuild /src/main/Hangman ./
CMD ["./Hangman"]